# Generated by Django 3.1.6 on 2021-05-19 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flip_or_ama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_no_yes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_no_yes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Price_range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Top_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_no_yes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_it_smartphone', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('short_line_to_define', models.CharField(default='ruhezz', max_length=150)),
                ('small_line', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=300, unique_for_date='publish')),
                ('thumbanil', models.ImageField(upload_to='thumbanils/')),
                ('banner_new', models.ImageField(upload_to='banners/')),
                ('para1', tinymce.models.HTMLField(blank=True, null=True)),
                ('para2', tinymce.models.HTMLField(blank=True, null=True)),
                ('para3', tinymce.models.HTMLField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=150, null=True)),
                ('dimensions', models.CharField(blank=True, default='---', max_length=150, null=True)),
                ('weight', models.CharField(blank=True, default='---', max_length=100, null=True)),
                ('material', models.CharField(blank=True, default='---', max_length=100, null=True)),
                ('no_sim', models.CharField(default='dual sim', max_length=20)),
                ('network_2g_3g', models.CharField(blank=True, default='2G,3G,4G', max_length=100, null=True)),
                ('wifi', models.CharField(blank=True, default='Yes, type: _', max_length=100, null=True)),
                ('bluetooth', models.CharField(blank=True, default='yes', max_length=100, null=True)),
                ('nfc', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('ir_blasster', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('battery_size', models.CharField(blank=True, default='__mAh', max_length=50, null=True)),
                ('removable_battery', models.CharField(blank=True, default='No', max_length=20, null=True)),
                ('charger_detail', models.CharField(blank=True, default='suported: In box(10wh)', max_length=50, null=True)),
                ('charge_0_to_100', models.CharField(blank=True, default='__', max_length=20, null=True)),
                ('backup', models.CharField(blank=True, default='__', max_length=20, null=True)),
                ('processor', models.CharField(blank=True, default='---', max_length=50, null=True)),
                ('os', models.CharField(blank=True, default='Andriod 11,  ', max_length=50, null=True)),
                ('antutu_score', models.CharField(blank=True, default='_', max_length=100, null=True)),
                ('camera_type', models.CharField(blank=True, default='Triple', max_length=20, null=True)),
                ('rear_camera_detail', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('video_resolutions', models.CharField(blank=True, default='4K@30fps, 1080p@30/60/120fps, 720p@960fps', max_length=50, null=True)),
                ('front_camera_detail', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('video_resolutions_front', models.CharField(blank=True, default=' 1080p@30/60fps, 720p@60fps', max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, default='FHD', max_length=50, null=True)),
                ('display_type', models.CharField(blank=True, default='Amled', max_length=50, null=True)),
                ('protection', models.CharField(blank=True, default='__', max_length=50, null=True)),
                ('storage_variant', models.CharField(blank=True, default='4GB 64GB, 6GB 128GB', max_length=100, null=True)),
                ('expandable', models.CharField(blank=True, default='Yes', max_length=10, null=True)),
                ('stero_speaker', models.CharField(blank=True, default='Yes', max_length=20, null=True)),
                ('headphone_jack', models.CharField(blank=True, default='Yes', max_length=20, null=True)),
                ('pricing1', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_pric1', models.CharField(blank=True, max_length=30, null=True)),
                ('img_link_logo1', models.CharField(blank=True, max_length=150, null=True)),
                ('pricing2', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_pric2', models.CharField(blank=True, max_length=30, null=True)),
                ('img_link_logo2', models.CharField(blank=True, max_length=150, null=True)),
                ('pricing3', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_pric3', models.CharField(blank=True, max_length=30, null=True)),
                ('img_link_logo3', models.CharField(blank=True, max_length=150, null=True)),
                ('pricing4', models.CharField(blank=True, max_length=30, null=True)),
                ('storage_pric4', models.CharField(blank=True, max_length=30, null=True)),
                ('img_link_logo4', models.CharField(blank=True, max_length=150, null=True)),
                ('smartphone_img_1', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_2', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_3', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_4', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_5', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_6', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_7', models.CharField(blank=True, max_length=500, null=True)),
                ('smartphone_img_8', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_1', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_2', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_3', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_4', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_5', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_6', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_7', models.CharField(blank=True, max_length=500, null=True)),
                ('rear_img_8', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_1', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_2', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_3', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_4', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_5', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_6', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_7', models.CharField(blank=True, max_length=500, null=True)),
                ('front_img_8', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.latest_release')),
                ('price_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.price_range')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('top_news_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.top_news')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Deal_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('link_item', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=102)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_width', models.CharField(default='60', max_length=50)),
                ('from_which', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.flip_or_ama')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
