# Generated by Django 3.1.6 on 2021-05-20 03:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adv',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dis',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
