# Generated by Django 3.1.6 on 2021-05-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210520_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_link_logo1',
            new_name='buy_link_1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img_link_logo2',
            new_name='buy_link_2',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img_link_logo3',
            new_name='buy_link_3',
        ),
    ]
