# Generated by Django 3.1.6 on 2021-05-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210520_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_link_logo4',
            new_name='buy_link_4',
        ),
    ]
